sudo: required
dist: trusty
services:
  - docker
language: go
go:
  - 1.8.3
before_install:
  - curl -L "${DOWNLOAD_URL}"/"${ETCD_VER}"/etcd-"${ETCD_VER}"-linux-amd64.tar.gz -o /tmp/etcd-"${ETCD_VER}"-linux-amd64.tar.gz;
  - mkdir -p /tmp/test-etcd && tar xzvf /tmp/etcd-"${ETCD_VER}"-linux-amd64.tar.gz -C /tmp/test-etcd --strip-components=1;
  - cp /tmp/test-etcd/etcd /usr/local/bin/
  - curl -L https://releases.hashicorp.com/consul/0.7.3/consul_0.7.3_linux_amd64.zip -o /tmp/consul.zip;
  - mkdir -p /tmp/test-consul && unzip /tmp/consul.zip -d /tmp/test-consul;
  - cp /tmp/test-consul/consul /usr/local/bin/
script:
  - make gotest
notifications:
  email:
    recipients:
      - aditya@portworx.com
    on_success: always
    on_failure: always
