sudo: required
dist: trusty
services:
- docker
language: go
go:
- 1.8.3
script:
- make docker-test
notifications:
    on_success: change
    on_failure: always
  email:
    recipients:
      - eng@portworx.com
after_success:
- bash <(curl -s https://codecov.io/bash)
